[project]
name = "trust-contract"
authors = []
description = ""
telemetry = true
requirements = []
[contracts.dispute-resolution]
path = "contracts/dispute-resolution.clar"
depends_on = []

[contracts.invoice-guard]
path = "contracts/invoice-guard.clar"
depends_on = []

[contracts.invoice-registry]
path = "contracts/invoice-registry.clar"
depends_on = []

[contracts.invoice-settlement]
path = "contracts/invoice-settlement.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
